-- PostgreSQL DDL for tech.ls_load_config
CREATE TABLE tech.ls_load_config (
    flow_name VARCHAR(100) NOT NULL,
    company_name VARCHAR(50) NOT NULL,
    load_type VARCHAR(5),
    active_flag VARCHAR(1),
    industry_sector VARCHAR(50) NOT NULL DEFAULT 'LIFESCIENCE',
    s_created_ts TIMESTAMP,
    s_modified_ts TIMESTAMP,
    selectors TEXT[],  -- Array of strings
    
    CONSTRAINT ls_load_config_pk PRIMARY KEY (flow_name, company_name)
);

-- Add table comment
COMMENT ON TABLE tech.ls_load_config IS 'Configuration details for data loading processes. Includes flow name, company, load type, and active status. The active flag indicates whether a configuration is currently in use, while timestamps track changes over time.';

-- Add column comments
COMMENT ON COLUMN tech.ls_load_config.flow_name IS 'Name of the data flow';
COMMENT ON COLUMN tech.ls_load_config.company_name IS 'Company associated with the configuration';
COMMENT ON COLUMN tech.ls_load_config.load_type IS 'Type of load being performed';
COMMENT ON COLUMN tech.ls_load_config.active_flag IS 'Indicates if configuration is active (Y/N)';
COMMENT ON COLUMN tech.ls_load_config.industry_sector IS 'Industry sector for sector-level staging schemas';
COMMENT ON COLUMN tech.ls_load_config.s_created_ts IS 'Timestamp when record was created';
COMMENT ON COLUMN tech.ls_load_config.s_modified_ts IS 'Timestamp when record was last modified';
COMMENT ON COLUMN tech.ls_load_config.selectors IS 'Array of CSS selectors for web scraping';


-- PostgreSQL DML for ls_load_config table
-- Note: In PostgreSQL, arrays are inserted using ARRAY[] syntax or '{element1,element2}' notation

INSERT INTO tech.ls_load_config (flow_name, company_name, load_type, active_flag, industry_sector, s_created_ts, s_modified_ts, selectors) VALUES
('LS_SOURCE_SCRAPING', 'ALLIANCE HEALTHCARE', 'FULL', 'Y', 'LIFESCIENCE', '2025-12-18 11:11:56', '2026-02-06 13:54:39.378', ARRAY['article a[href]','.news a[href]','.press a[href]','.story a[href]','.post a[href]','.card a[href]','.tile a[href]','.item a[href]','a[href*=press]','a[href*=news]','a[href*=article]','a[href*=media]','a[href*=stories]','a[href*=news-releases]','.article a[href]','.article-link a[href]','.release a[href]','.press-release a[href]','a[href*=/202[0-9]/]','a[href*=202[0-9]/]','a[href*=article/]','a[href*=news/]','a[href*=press-release/]','a[href*=reports/]','a[href*=insights/]','a[href*=analysis/]','a[href*=media/]','a[href*=features/]','a[href*=//sub. ]','a[href*=//news. ]','a[href*=//press. ]','a[href^=https:// i][href*=// i][href*=.]']),
('LS_SOURCE_SCRAPING', 'ASTERA', 'FULL', 'Y', 'LIFESCIENCE', '2025-12-18 11:11:56', '2026-02-06 13:54:39.378', ARRAY['article a[href]','.news a[href]','.press a[href]','.story a[href]','.post a[href]','.card a[href]','.tile a[href]','.item a[href]','a[href*=press]','a[href*=news]','a[href*=article]','a[href*=media]','a[href*=stories]','a[href*=news-releases]','.article a[href]','.article-link a[href]','.release a[href]','.press-release a[href]','a[href*=/202[0-9]/]','a[href*=202[0-9]/]','a[href*=article/]','a[href*=news/]','a[href*=press-release/]','a[href*=reports/]','a[href*=insights/]','a[href*=analysis/]','a[href*=media/]','a[href*=features/]','a[href*=//sub. ]','a[href*=//news. ]','a[href*=//press. ]','a[href^=https:// i][href*=// i][href*=.]']),
('LS_SOURCE_SCRAPING', 'BIOCODEX', 'FULL', 'Y', 'LIFESCIENCE', '2025-12-18 11:11:56', '2026-02-06 13:54:39.378', ARRAY['article a[href]','.news a[href]','.press a[href]','.story a[href]','.post a[href]','.card a[href]','.tile a[href]','.item a[href]','a[href*=press]','a[href*=news]','a[href*=article]','a[href*=media]','a[href*=stories]','a[href*=news-releases]','.article a[href]','.article-link a[href]','.release a[href]','.press-release a[href]','a[href*=/202[0-9]/]','a[href*=202[0-9]/]','a[href*=article/]','a[href*=news/]','a[href*=press-release/]','a[href*=reports/]','a[href*=insights/]','a[href*=analysis/]','a[href*=media/]','a[href*=features/]','a[href*=//sub. ]','a[href*=//news. ]','a[href*=//press. ]','a[href^=https:// i][href*=// i][href*=.]']),
('LS_SOURCE_SCRAPING', 'CEVA SANTE', 'FULL', 'Y', 'LIFESCIENCE', '2025-12-18 11:11:56', '2026-02-06 13:54:39.378', ARRAY['article a[href]','.news a[href]','.press a[href]','.story a[href]','.post a[href]','.card a[href]','.tile a[href]','.item a[href]','a[href*=press]','a[href*=news]','a[href*=article]','a[href*=media]','a[href*=stories]','a[href*=news-releases]','.article a[href]','.article-link a[href]','.release a[href]','.press-release a[href]','a[href*=/202[0-9]/]','a[href*=202[0-9]/]','a[href*=article/]','a[href*=news/]','a[href*=press-release/]','a[href*=reports/]','a[href*=insights/]','a[href*=analysis/]','a[href*=media/]','a[href*=features/]','a[href*=//sub. ]','a[href*=//news. ]','a[href*=//press. ]','a[href^=https:// i][href*=// i][href*=.]']),
('LS_SOURCE_SCRAPING', 'DELPHARM', 'FULL', 'Y', 'LIFESCIENCE', '2025-12-18 11:11:56', '2026-02-06 13:54:39.378', ARRAY['article a[href]','.news a[href]','.press a[href]','.story a[href]','.post a[href]','.card a[href]','.tile a[href]','.item a[href]','a[href*=press]','a[href*=news]','a[href*=article]','a[href*=media]','a[href*=stories]','a[href*=news-releases]','.article a[href]','.article-link a[href]','.release a[href]','.press-release a[href]','a[href*=/202[0-9]/]','a[href*=202[0-9]/]','a[href*=article/]','a[href*=news/]','a[href*=press-release/]','a[href*=reports/]','a[href*=insights/]','a[href*=analysis/]','a[href*=media/]','a[href*=features/]','a[href*=//sub. ]','a[href*=//news. ]','a[href*=//press. ]','a[href^=https:// i][href*=// i][href*=.]']),
('LS_SOURCE_SCRAPING', 'EUROFINS', 'FULL', 'Y', 'LIFESCIENCE', '2025-12-18 11:11:56', '2026-02-06 13:54:39.378', ARRAY['article a[href]','.news a[href]','.press a[href]','.story a[href]','.post a[href]','.card a[href]','.tile a[href]','.item a[href]','a[href*=press]','a[href*=news]','a[href*=article]','a[href*=media]','a[href*=stories]','a[href*=news-releases]','.article a[href]','.article-link a[href]','.release a[href]','.press-release a[href]','a[href*=/202[0-9]/]','a[href*=202[0-9]/]','a[href*=article/]','a[href*=news/]','a[href*=press-release/]','a[href*=reports/]','a[href*=insights/]','a[href*=analysis/]','a[href*=media/]','a[href*=features/]','a[href*=//sub. ]','a[href*=//news. ]','a[href*=//press. ]','a[href^=https:// i][href*=// i][href*=.]']),
('LS_SOURCE_SCRAPING', 'FAREVA', 'DELTA', 'Y', 'LIFESCIENCE', '2025-12-18 11:11:56', '2026-04-17 22:17:03.327', ARRAY['article a[href]','.news a[href]','.press a[href]','.story a[href]','.post a[href]','.card a[href]','.tile a[href]','.item a[href]','a[href*=press]','a[href*=news]','a[href*=article]','a[href*=media]','a[href*=stories]','a[href*=news-releases]','.article a[href]','.article-link a[href]','.release a[href]','.press-release a[href]','a[href*=/202[0-9]/]','a[href*=202[0-9]/]','a[href*=article/]','a[href*=news/]','a[href*=press-release/]','a[href*=reports/]','a[href*=insights/]','a[href*=analysis/]','a[href*=media/]','a[href*=features/]','a[href*=//sub. ]','a[href*=//news. ]','a[href*=//press. ]','a[href^=https:// i][href*=// i][href*=.]']),
('LS_SOURCE_SCRAPING', 'GALDERMA', 'DELTA', 'Y', 'LIFESCIENCE', '2025-12-18 11:11:56', '2026-04-17 22:16:43.630', ARRAY['article a[href]','.news a[href]','.press a[href]','.story a[href]','.post a[href]','.card a[href]','.tile a[href]','.item a[href]','a[href*=press]','a[href*=news]','a[href*=article]','a[href*=media]','a[href*=stories]','a[href*=news-releases]','.article a[href]','.article-link a[href]','.release a[href]','.press-release a[href]','a[href*=/202[0-9]/]','a[href*=202[0-9]/]','a[href*=article/]','a[href*=news/]','a[href*=press-release/]','a[href*=reports/]','a[href*=insights/]','a[href*=analysis/]','a[href*=media/]','a[href*=features/]','a[href*=//sub. ]','a[href*=//news. ]','a[href*=//press. ]','a[href^=https:// i][href*=// i][href*=.]']),
('LS_SOURCE_SCRAPING', 'HAELON', 'FULL', 'Y', 'LIFESCIENCE', '2025-12-18 11:11:56', '2026-02-06 13:54:39.378', ARRAY['article a[href]','.news a[href]','.press a[href]','.story a[href]','.post a[href]','.card a[href]','.tile a[href]','.item a[href]','a[href*=press]','a[href*=news]','a[href*=article]','a[href*=media]','a[href*=stories]','a[href*=news-releases]','.article a[href]','.article-link a[href]','.release a[href]','.press-release a[href]','a[href*=/202[0-9]/]','a[href*=202[0-9]/]','a[href*=article/]','a[href*=news/]','a[href*=press-release/]','a[href*=reports/]','a[href*=insights/]','a[href*=analysis/]','a[href*=media/]','a[href*=features/]','a[href*=//sub. ]','a[href*=//news. ]','a[href*=//press. ]','a[href^=https:// i][href*=// i][href*=.]']),
('LS_SOURCE_SCRAPING', 'IPSEN', 'DELTA', 'Y', 'LIFESCIENCE', '2025-12-18 11:11:56', '2026-04-17 22:17:13.298', ARRAY['article a[href]','.news a[href]','.press a[href]','.story a[href]','.post a[href]','.card a[href]','.tile a[href]','.item a[href]','a[href*=press]','a[href*=news]','a[href*=article]','a[href*=media]','a[href*=stories]','a[href*=news-releases]','.article a[href]','.article-link a[href]','.release a[href]','.press-release a[href]','a[href*=/202[0-9]/]','a[href*=202[0-9]/]','a[href*=article/]','a[href*=news/]','a[href*=press-release/]','a[href*=reports/]','a[href*=insights/]','a[href*=analysis/]','a[href*=media/]','a[href*=features/]','a[href*=//sub. ]','a[href*=//news. ]','a[href*=//press. ]','a[href^=https:// i][href*=// i][href*=.]']),
('LS_SOURCE_SCRAPING', 'LILLY', 'FULL', 'Y', 'LIFESCIENCE', '2025-12-18 11:11:56', '2026-02-06 13:54:39.378', ARRAY['article a[href]','.news a[href]','.press a[href]','.story a[href]','.post a[href]','.card a[href]','.tile a[href]','.item a[href]','a[href*=press]','a[href*=news]','a[href*=article]','a[href*=media]','a[href*=stories]','a[href*=news-releases]','.article a[href]','.article-link a[href]','.release a[href]','.press-release a[href]','a[href*=/202[0-9]/]','a[href*=202[0-9]/]','a[href*=article/]','a[href*=news/]','a[href*=press-release/]','a[href*=reports/]','a[href*=insights/]','a[href*=analysis/]','a[href*=media/]','a[href*=features/]','a[href*=//sub. ]','a[href*=//news. ]','a[href*=//press. ]','a[href^=https:// i][href*=// i][href*=.]']),
('LS_SOURCE_SCRAPING', 'OPELLA', 'DELTA', 'Y', 'LIFESCIENCE', '2025-12-18 11:11:56', '2026-04-17 22:16:36.680', ARRAY['article a[href]','.news a[href]','.press a[href]','.story a[href]','.post a[href]','.card a[href]','.tile a[href]','.item a[href]','a[href*=press]','a[href*=news]','a[href*=article]','a[href*=media]','a[href*=stories]','a[href*=news-releases]','.article a[href]','.article-link a[href]','.release a[href]','.press-release a[href]','a[href*=/202[0-9]/]','a[href*=202[0-9]/]','a[href*=article/]','a[href*=news/]','a[href*=press-release/]','a[href*=reports/]','a[href*=insights/]','a[href*=analysis/]','a[href*=media/]','a[href*=features/]','a[href*=//sub. ]','a[href*=//news. ]','a[href*=//press. ]','a[href^=https:// i][href*=// i][href*=.]']),
('LS_SOURCE_SCRAPING', 'OXIPHARM', 'DELTA', 'Y', 'LIFESCIENCE', '2025-12-18 11:11:56', '2026-04-17 22:16:48.625', ARRAY['article a[href]','.news a[href]','.press a[href]','.story a[href]','.post a[href]','.card a[href]','.tile a[href]','.item a[href]','a[href*=press]','a[href*=news]','a[href*=article]','a[href*=media]','a[href*=stories]','a[href*=news-releases]','.article a[href]','.article-link a[href]','.release a[href]','.press-release a[href]','a[href*=/202[0-9]/]','a[href*=202[0-9]/]','a[href*=article/]','a[href*=news/]','a[href*=press-release/]','a[href*=reports/]','a[href*=insights/]','a[href*=analysis/]','a[href*=media/]','a[href*=features/]','a[href*=//sub. ]','a[href*=//news. ]','a[href*=//press. ]','a[href^=https:// i][href*=// i][href*=.]']),
('LS_SOURCE_SCRAPING', 'PIERRE FABRE', 'DELTA', 'Y', 'LIFESCIENCE', '2025-12-18 11:11:56', '2026-04-17 22:16:31.404', ARRAY['article a[href]','.news a[href]','.press a[href]','.story a[href]','.post a[href]','.card a[href]','.tile a[href]','.item a[href]','a[href*=press]','a[href*=news]','a[href*=article]','a[href*=media]','a[href*=stories]','a[href*=news-releases]','.article a[href]','.article-link a[href]','.release a[href]','.press-release a[href]','a[href*=/202[0-9]/]','a[href*=202[0-9]/]','a[href*=article/]','a[href*=news/]','a[href*=press-release/]','a[href*=reports/]','a[href*=insights/]','a[href*=analysis/]','a[href*=media/]','a[href*=features/]','a[href*=//sub. ]','a[href*=//news. ]','a[href*=//press. ]','a[href^=https:// i][href*=// i][href*=.]']),
('LS_SOURCE_SCRAPING', 'SANOFI', 'DELTA', 'Y', 'LIFESCIENCE', '2025-12-18 11:11:56', '2026-04-17 22:16:55.379', ARRAY['article a[href]','.news a[href]','.press a[href]','.story a[href]','.post a[href]','.card a[href]','.tile a[href]','.item a[href]','a[href*=press]','a[href*=news]','a[href*=article]','a[href*=media]','a[href*=stories]','a[href*=news-releases]','.article a[href]','.article-link a[href]','.release a[href]','.press-release a[href]','a[href*=/202[0-9]/]','a[href*=202[0-9]/]','a[href*=article/]','a[href*=news/]','a[href*=press-release/]','a[href*=reports/]','a[href*=insights/]','a[href*=analysis/]','a[href*=media/]','a[href*=features/]','a[href*=//sub. ]','a[href*=//news. ]','a[href*=//press. ]','a[href^=https:// i][href*=// i][href*=.]']),
('LS_SOURCE_SCRAPING', 'SEBIA', 'FULL', 'Y', 'LIFESCIENCE', '2025-12-18 11:11:56', '2026-02-06 13:54:39.378', ARRAY['article a[href]','.news a[href]','.press a[href]','.story a[href]','.post a[href]','.card a[href]','.tile a[href]','.item a[href]','a[href*=press]','a[href*=news]','a[href*=article]','a[href*=media]','a[href*=stories]','a[href*=news-releases]','.article a[href]','.article-link a[href]','.release a[href]','.press-release a[href]','a[href*=/202[0-9]/]','a[href*=202[0-9]/]','a[href*=article/]','a[href*=news/]','a[href*=press-release/]','a[href*=reports/]','a[href*=insights/]','a[href*=analysis/]','a[href*=media/]','a[href*=features/]','a[href*=//sub. ]','a[href*=//news. ]','a[href*=//press. ]','a[href^=https:// i][href*=// i][href*=.]']),
('LS_SOURCE_SCRAPING', 'SERVIER', 'DELTA', 'Y', 'LIFESCIENCE', '2025-12-18 11:11:56', '2026-04-17 22:16:40.098', ARRAY['article a[href]','.news a[href]','.press a[href]','.story a[href]','.post a[href]','.card a[href]','.tile a[href]','.item a[href]','a[href*=press]','a[href*=news]','a[href*=article]','a[href*=media]','a[href*=stories]','a[href*=news-releases]','.article a[href]','.article-link a[href]','.release a[href]','.press-release a[href]','a[href*=/202[0-9]/]','a[href*=202[0-9]/]','a[href*=article/]','a[href*=news/]','a[href*=press-release/]','a[href*=reports/]','a[href*=insights/]','a[href*=analysis/]','a[href*=media/]','a[href*=features/]','a[href*=//sub. ]','a[href*=//news. ]','a[href*=//press. ]','a[href^=https:// i][href*=// i][href*=.]']),
('LS_SOURCE_SCRAPING', 'STAGO', 'DELTA', 'Y', 'LIFESCIENCE', '2025-12-18 11:11:56', '2026-04-17 22:17:10.112', ARRAY['article a[href]','.news a[href]','.press a[href]','.story a[href]','.post a[href]','.card a[href]','.tile a[href]','.item a[href]','a[href*=press]','a[href*=news]','a[href*=article]','a[href*=media]','a[href*=stories]','a[href*=news-releases]','.article a[href]','.article-link a[href]','.release a[href]','.press-release a[href]','a[href*=/202[0-9]/]','a[href*=202[0-9]/]','a[href*=article/]','a[href*=news/]','a[href*=press-release/]','a[href*=reports/]','a[href*=insights/]','a[href*=analysis/]','a[href*=media/]','a[href*=features/]','a[href*=//sub. ]','a[href*=//news. ]','a[href*=//press. ]','a[href^=https:// i][href*=// i][href*=.]']),
('LS_SOURCE_SCRAPING', 'VIATRIS', 'FULL', 'Y', 'LIFESCIENCE', '2026-01-28 09:06:40.227', '2026-02-06 13:54:39.378', ARRAY['article a[href]','.news a[href]','.press a[href]','.story a[href]','.post a[href]','.card a[href]','.tile a[href]','.item a[href]','a[href*=press]','a[href*=news]','a[href*=article]','a[href*=media]','a[href*=stories]','a[href*=news-releases]','.article a[href]','.article-link a[href]','.release a[href]','.press-release a[href]','a[href*=/202[0-9]/]','a[href*=202[0-9]/]','a[href*=article/]','a[href*=news/]','a[href*=press-release/]','a[href*=reports/]','a[href*=insights/]','a[href*=analysis/]','a[href*=media/]','a[href*=features/]','a[href*=//sub. ]','a[href*=//news. ]','a[href*=//press. ]','a[href^=https:// i][href*=// i][href*=.]']),
('LS_SOURCE_SCRAPING', 'VIRBAC', 'DELTA', 'Y', 'LIFESCIENCE', '2025-12-18 11:11:56', '2026-04-17 22:16:52.243', ARRAY['article a[href]','.news a[href]','.press a[href]','.story a[href]','.post a[href]','.card a[href]','.tile a[href]','.item a[href]','a[href*=press]','a[href*=news]','a[href*=article]','a[href*=media]','a[href*=stories]','a[href*=news-releases]','.article a[href]','.article-link a[href]','.release a[href]','.press-release a[href]','a[href*=/202[0-9]/]','a[href*=202[0-9]/]','a[href*=article/]','a[href*=news/]','a[href*=press-release/]','a[href*=reports/]','a[href*=insights/]','a[href*=analysis/]','a[href*=media/]','a[href*=features/]','a[href*=//sub. ]','a[href*=//news. ]','a[href*=//press. ]','a[href^=https:// i][href*=// i][href*=.]']);
